export const GENRES = [
    'Tất cả thể loại',
    'Action',
    'Adult',
    'Adventure',
    'Anime',
    'Chuyển Sinh',
    'Comedy',
    'Comic',
    'Cooking',
    'Cổ Đại',
    'Doujinshi',
    'Drama',
    'Đam Mỹ',
    'Ecchi',
    'Fantasy',
    'Gender Bender',
    'Harem',
    'Historical',
    'Horror',
    'Josei',
    'Live action',
    'Manga',
    'Manhua',
    'Manhwa',
    'Martial Arts',
    'Mature',
    'Mecha',
    'Mystery',
    'Ngôn Tình',
    'One shot',
    'Psychological',
    'Romance',
    'School Life',
    'Sci-fi',
    'Seinen',
    'Shoujo',
    'Shoujo Ai',
    'Shounen',
    'Shounen Ai',
    'Slice of Life',
    'Smut',
    'Soft Yaoi',
    'Soft Yuri',
    'Sports',
    'Supernatural',
    'Tạp chí truyện tranh',
    'Thiếu Nhi',
    'Tragedy',
    'Trinh Thám',
    'Truyện scan',
    'Truyện Màu',
    'Việt Nam',
    'Webtoon',
    'Xuyên Không',
    '16+',
] as const;
